name: AutoFormer

params:
  moving_avg: 25
  d_model: 128
  factor: 3
  n_heads: 4
  dropout: 0.05
  d_ff: 2048
  e_layers: 4

hyperparameters_vary:
  dropout:
    optuna_type: float
    low: 0.1
    high: 0.7
    step: 0.1

attack_train_mode: True
  
    