name: CrossFormer

params:
  modes: 32
  mode_select: 'random'
  version:  'Fourier' # version = 'Wavelets'
  moving_avg: 24 #, 24]
  seq_len: ${dataset.seq_len}
  enc_in: 1
  d_model: 128
  dropout: 0.15
  n_heads: 8
  d_ff: 256
  e_layers: 3
  activation: 'gelu'
  embed: timeF
  freq: s
  des: Exp
  top_k: 3
  factor: 1
  output_attention: 'store_true'

hyperparameters_vary:
  dropout:
    optuna_type: float
    low: 0.1
    high: 0.7
    step: 0.1

attack_train_mode: False
