name: FEDformer

params:
  modes: 32
  mode_select: 'random'
  version:  'Fourier' # version = 'Wavelets'
  moving_avg: 24 #, 24]
  seq_len: ${dataset.seq_len}
  enc_in: 1
  d_model: 128
  dropout: 0.15
  n_heads: 8
  d_ff: 1024
  e_layers: 4
  activation: 'gelu'
  embed: timeF
  freq: s
hyperparameters_vary:
  dropout:
    optuna_type: float
    low: 0.1
    high: 0.7
    step: 0.1

attack_train_mode: False
