slice: False
use_disc_check: True
test_run: False # If true results will be not saved!!!!
exp_name: '_MULTI'
exp_model_name: '_MULTI'

model_folder: checkpoints/${dataset.name}/${attack_model.name}/${exp_model_name}
disc_path: results/${dataset.name}/${attack_model.name}/discriminator/fgsm_attack_${exp_name}
save_path: results/${dataset.name}/${attack_model.name}/attack/${attack.short_name}${exp_name}

model_id_attack: 100

defaults:
  - dataset: Strawberry
  - model@attack_model: TST
  - model@disc_model_reg: TST
  - model@disc_model_check: TST
  - attack: FGSMDisc

criterion_name: BCELoss
criterion_params: null

batch_size: 64
estimator_batch_size: null
cuda: 'cuda:3'

metric_effect: F1
metric_hid: ROC_AUC_DISC

list_check_model_params:
  - model_id : ${model_id_attack}
    model_name: fgsm_attack_eps=0.03_nsteps=10

enable_optimization: False
optuna_optimizer:
  n_trials: 5
  sampler:
    _target_: optuna.samplers.TPESampler
    seed: 0
  pruner:
    _target_: optuna.pruners.MedianPruner
  hyperparameters_vary:
    ${attack.hyperparameters_vary}
