name: FordA
num_classes: 2
seq_len: 500
total_object_count: 1598
train:
  object_count: 799
  max: .nan
  mean: .nan
  min: .nan
  roughness: .nan
test:
  object_count: 799
  max: .nan
  mean: .nan
  min: .nan
  roughness: .nan
