name: FreezerRegularTrain
num_classes: 2
seq_len: 301
total_object_count: 1512
train:
  object_count: 150
  max: 5.0221355
  mean: 9.361460188311934e-11
  min: -2.2294504
  roughness: 0.044626377470920846
test:
  object_count: 1362
  max: .nan
  mean: .nan
  min: .nan
  roughness: .nan
